// Automatically generated by make_root_pointers.py.
// harnessDroid addition: the pre-allocated cancellation exception lives in the
// GC heap and must be rooted here, or the collector frees it and the SIGURG
// handler dereferences freed memory (SIGSEGV SI_KERNEL on-device).

mp_obj_list_t mp_sys_argv_obj;
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
mp_obj_t vm_cancel_exception;
